# Script for studying the use of graphs in python:

In [1]:
import numpy as np
from random import uniform,randint
import matplotlib.pyplot as plt
from scipy.spatial.distance import mahalanobis
from scipy import signal
import networkx as nx
import math
from numpy import meshgrid
#import jgraph as ig
from six.moves import input

In [2]:
from modules.distances import l1dist, l2dist, distgraph

In [3]:
## Sorting point masses into the 2D space:
xmin = -10.0
xmax = +10.0
ymin = -10.0
ymax = +10.0
npoints = 20
x = np.zeros(npoints)
y = np.zeros(npoints)
node = np.zeros(npoints)

In [4]:
for i in range(npoints):
    node[i] = int(i)
    x[i] = uniform(xmin,xmax)
    y[i] = uniform(ymin,ymax)
print (x), y, node

[-2.4994077  -0.6392563  -0.89914935 -5.17979699 -4.71146748  6.03099054
 -0.02604369  5.8260254   7.0259983  -1.60905052 -4.61763032  1.97827024
 -8.010162   -2.80409781  8.20629294 -2.83120919  7.22043956 -1.91526508
 -5.19348181 -8.96532823] [-1.21413798e+00 -4.87106843e+00  2.65425667e+00  4.15820962e-01
 -3.29302044e+00  2.88294643e+00 -8.17274143e+00 -2.24568296e+00
  7.01010903e+00 -6.37247810e+00 -7.73650523e-03  2.93171315e+00
 -4.04922178e+00 -4.52407224e+00  1.47844261e+00  8.12644029e+00
  4.02852242e+00  5.72317934e+00  1.00291049e+00 -9.08157153e+00] [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [17]:
M = np.array( (x,y) )
C = np.cov( M.T )
IC = np.eye(20)
print IC

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

In [16]:
invC = np.linalg.inv(C)
print np.shape(invC)

invC *=1.0

(20, 20)


In [22]:
mahalanobis(x,y, IC )

23.29626921724097

In [27]:
print np.sqrt(np.dot( (x-y),(x-y) ))

23.29626921724097


In [ ]:
###--------##########################
plt.figure( figsize=(10,10), facecolor='w' )
p1 = plt.plot(x, y, color='red', marker='o', linestyle='solid',
        linewidth=1, markersize=16 )

plt.title('Bolinhas')
plt.grid()

plt.xlim( min(x)-1.0, max(x)+1.0 )
plt.ylim( min(y)-1.0, max(y)+1.0 )

plt.gca().invert_yaxis()
plt.savefig('test_graph.png',dpi=300,transparent=True)
plt.show()

In [ ]:
# Lets see what's going on here:
S = nx.Graph()
for i in range(npoints):
    S.add_node(i ,pos=(x[i],y[i]))
    for j in range(npoints):
        S.add_edge(i,j,weight=l2dist(x,y)[i][j])
TS = nx.minimum_spanning_tree(S)

In [ ]:
plt.figure(figsize=(12,6))
plt.subplot(121)
nx.draw(S)
plt.subplot(122)
nx.draw(TS)
plt.show()

In [ ]:
#TENTANDO COLOCAR LABELS NOS VERTICES
nx.draw(TS, with_labels = True)
plt.savefig('labels.png')

# TODO: Entender as saidas do MST para podermos calcular a funcao de equidistancia para calcular a funcao $\theta$

># <center> $\theta = \sum_i (d_{mst}^i - \overline{d_{mst}})^2$

In [ ]:
#CALCULANDO O PHI VIA A FUNCAO CRIADA
phi, dmst = distgraph(TS)
print(phi, dmst)

In [ ]:
### Plot da Arvore Minima em coordenadas 2D:
plt.figure( figsize=(10,10), facecolor='w' )
bbox_props = dict(boxstyle="round,pad=0.1", fc="white", ec="b", lw=1)

for (i, j, d) in TS.edges.data('weight'):
    xt = [ x[i], x[j] ]
    yt = [ y[i], y[j] ]
    print i, x[i] ,y[i] , j, x[j] , y[j]
    plt.annotate( int(node[i]), xy=(x[i],y[i]) , bbox=bbox_props)
    plt.annotate( int(node[j]), xy=(x[j],y[j]) , bbox=bbox_props)
    plt.plot(xt,yt,'.-')

plt.grid()
p1 = plt.plot(x, y, 'ko', marker='o' )
plt.gca().invert_yaxis()
#plt.savefig('L2dist.pdf')
plt.show()

# TODO: Fazer testes simples para verificar a função distGraf:
> 1) um circulo de pontos igualmente espaçados e aleatorios; <br>
> 2) um retangulo de pontos igualmente espaçados e aleatórios; <br>
> 3) plotar a àrvore com os índices dos vértices para identificação;<br>

In [ ]:
#PLOTA UM L PARA TESTAR A FUNCAO DISTGRAPH E O NETWORKX
ax = np.linspace(-5,5,npoints)
ay = np.zeros(npoints)
ay = 5 + ay
by = np.linspace(-5,5,npoints)
bx = np.zeros(npoints)
bx = -5 + bx
ax1 = np.linspace(-5,5,npoints)
ay1 = np.zeros(npoints)
ay1 = -5 + ay1
by1 = np.linspace(-5,5,npoints)
bx1 = np.zeros(npoints)
bx1 = 5 + bx1

a = np.zeros(2*npoints)
b = np.zeros(2*npoints)

for i in range(0,npoints):
    a[i] = ax[i]
for i in range(npoints,2*npoints):
    a[i] = ay[i - npoints]
b = np.zeros(2*npoints)
for i in range(0,npoints):
    b[i] = bx[i]
for i in range(npoints+1,2*npoints):
    b[i] = by[i - npoints]
L = (a,b)
plt.plot(a,b)
plt.grid()
plt.show()

In [ ]:
S1 = nx.Graph()
for i in range(2*npoints):
    S1.add_node(i ,pos=(L[0][i],L[1][i]))
    for j in range(2*npoints):
        S1.add_edge(i,j,weight=l2dist(a,b)[i][j])
TS1 = nx.minimum_spanning_tree(S1)

In [ ]:
plt.figure(figsize=(12,6))
plt.subplot(121)
nx.draw(S1)
plt.subplot(122)
nx.draw(TS1)
plt.show()

In [ ]:
#Calculating the phi funtcion and the mean
phi1, dmst1 = distgraph(TS1)
print(phi1, dmst1) #this makes sense since the average is close enough to every point

In [ ]:
### Plot da Arvore Minima em coordenadas 2D:
plt.figure( figsize=(10,10) )
for (i, j, d) in TS1.edges.data('weight'): 
    print(d)
    at = [ a[i], a[j] ]
    bt = [ b[i], b[j] ]
    plt.plot(at,bt,'.-')
plt.grid()
plt.savefig('L2dist.pdf')
plt.show()

In [ ]:
np.cov